spring.application.name=amadeus

server.port=${PORT:8080}

amadeus.soap.endpoint=${AMADEUS_SOAP_ENDPOINT:https://nodeD2.test.webservices.amadeus.com/1ASIWPROG8T}
amadeus.soap.auth.user-id=${AMADEUS_SOAP_AUTH_USER_ID:WSG8TPRO}
amadeus.soap.auth.password=${AMADEUS_SOAP_AUTH_PASSWORD:gX$EBg2Nj2RP}
amadeus.soap.auth.office-id=${AMADEUS_SOAP_AUTH_OFFICE_ID:PARFT2796}
amadeus.soap.auth.agent-duty-code=${AMADEUS_SOAP_AUTH_AGENT_DUTY_CODE:SU}
amadeus.soap.auth.pos-type=${AMADEUS_SOAP_AUTH_POS_TYPE:1}
amadeus.soap.auth.requestor-type=${AMADEUS_SOAP_AUTH_REQUESTOR_TYPE:U}

logging.level.org.springframework.ws.client.MessageTracing.sent=${SPRING_WS_TRACE_SENT:TRACE}
logging.level.org.springframework.ws.client.MessageTracing.received=${SPRING_WS_TRACE_RECEIVED:TRACE}

# Ensure Swagger/OpenAPI uses the HTTPS scheme when behind a proxy.
server.forward-headers-strategy=framework

security.api-key.header-name=${API_KEY_HEADER_NAME:X-API-KEY}
security.api-key.value=${API_KEY:42z09CMAZQr6IzHlgra6xKadGo1jWK31}
